version: "1"

envVarGroups:
  - name: weather-backend-secrets
    envVars:
      - key: DATASOURCE_URL
        sync: false
      - key: DATASOURCE_USERNAME
        sync: false
      - key: DATASOURCE_PASSWORD
        sync: false

services:
  - type: web
    name: weather-backend
    env: docker
    plan: free
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: PORT
        value: "8080"
    envVarGroups:
      - weather-backend-secrets

  - type: web
    name: weather-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        fromService:
          name: weather-backend
          type: web
          property: host
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
