version: "1"

services:
  - type: web
    name: weather-backend
    env: docker
    plan: free
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: PORT
        value: "8080"
      - key: DATASOURCE_URL
        fromDatabase:
          name: weather-app-db
          property: connectionString
      - key: DATASOURCE_USERNAME
        fromDatabase:
          name: weather-app-db
          property: user
      - key: DATASOURCE_PASSWORD
        fromDatabase:
          name: weather-app-db
          property: password

  - type: web
    name: weather-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        fromService:
          name: weather-backend
          type: web
          property: host
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"

databases:
  - name: weather-app-db
    plan: starter
    databaseName: weather_app
    user: weather_app
