spring:
  application:
    name: weather-backend
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/weather_app}
    username: ${DATASOURCE_USERNAME:weather_app}
    password: ${DATASOURCE_PASSWORD:weather_app}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: ${PORT:8080}
weather:
  open-meteo:
    base-url: https://api.open-meteo.com/v1
    timeout-seconds: 5
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    com.example.weatherapp: INFO
